#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

my_laptop_external_monitor=$(xrandr --query | grep 'HDMI-1-3')
if [[ $my_laptop_external_monitor = *connected* ]]; then
    xrandr --output HDMI-1-3 --primary --mode 1920x1080 --rotate normal --output eDP-1 --mode 1920x1080 --rotate normal --right-of HDMI-1-3 
fi

$HOME/.config/polybar/launch.sh

if [[ $my_laptop_external_monitor = *connected* ]]; then
	bspc monitor eDP-1 -d 4 5 6 7 8 9 10
	bspc monitor HDMI-1-3 -d 1 2 3
else 
	bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^1'
bspc rule -a thunderbird desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
