#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

my_laptop_external_monitor=$(xrandr --query | grep 'HDMI-1-3')
if [[ $my_laptop_external_monitor = *connected* ]]; then
    xrandr --output HDMI-1-3 --primary --mode 1920x1080 --rotate normal --output eDP-1 --mode 1920x1080 --rotate normal --right-of HDMI-1-3 
fi

$HOME/.config/polybar/launch.sh

if [[ $my_laptop_external_monitor = *connected* ]]; then
	bspc monitor eDP-1 -d 4 5 6 7 8 9 10
	bspc monitor HDMI-1-3 -d 1 2 3
else 
	bspc monitor HDMI-3 -d 1 2 3 4 5 6 7 8 9 10
fi

bspc config border_width         2
bspc config focused_border_color \#086800
bspc config window_gap          12
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

