#!/usr/bin/bash 

RED="\e[0;91m"
BLUE="\e[0;94m"
GREEN="\e[0;92m"
BOLD="\e[1m"
RESET="\e[0m"

function pipPackages() {
  printf "${BLUE}[${GREEN}*${BLUE}]${BOLD} Installing pip packages${RESET}\n"
	pip3 install jedi pwntools pycryptodome \
		setuptools yara python-socketio pyelftools \
		websockets urllib3 binwalk pwntools sqlite \
		netifaces iptools pyopenssl;
}

function sublimeText() {
  printf "${BLUE}[${GREEN}*${BLUE}]${BOLD} Installing sublime${RESET}\n"
	wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/sublimehq-archive.gpg;
	echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list;
	apt-get update;
	apt-get install sublime-text -y;
}

function __offsec__ () {
  printf "${BLUE}[${GREEN}*${BLUE}]${BOLD} Updating system${RESET}\n"
  apt-get update && apt-get upgrade -y;
  
  printf "${BLUE}[${GREEN}*${BLUE}]${BOLD} Installing packages from apt repos${RESET}\n"
  apt-get install -y git tmux gcc make perl \
    guake openvpn nmap docker.io \
    wireshark exiftool steghide gobuster \
    hexedit nikto \
    vagrant gimp \
    scapy tcpflow \
    libcompress-raw-lzma-perl \
    apt-transport-https zsh neovim meson \
    ninja-build libx11-dev libxinerama-dev \
    libxft-dev libxrandr-dev build-essential \
    autoconf automake;

 pipPackages
 sublimeText
}

